Avoid polutting global namespace with `OK` define.
Fixes clash with playready:

sysroots/dcx960-debug/usr/include/playready3x/bignum.h: In function 'DRM_BOOL PK::multiply(const digit_t*, DRM_DWORD, const digit_t*, DRM_DWORD, digit_t*)':
sysroots/dcx960-debug/usr/include/playready3x/bignum.h:565:21: error: lvalue required as left operand of assignment
         DRM_BOOL OK = TRUE;                                             \
                     ^